version: "1.0"
services:
  backend:
    restart: always
    container_name: backend
    command : python manage.py runserver 0.0.0.0:8000
    build:
      context: ./backend-django/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - db-net

  frontend:
    restart: always
    command : npm start
    container_name: frontend
    build:
      context: ./frontend-reactjs/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db-net

networks:
  db-net:
    driver: bridge