# Generated by Django 3.2.13 on 2022-07-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='updatedAt',
            field=models.CharField(blank=True, default='13:14:25', max_length=180),
        ),
    ]
