# Generated by Django 3.2.13 on 2022-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_auto_20220716_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='updatedAt',
            field=models.CharField(blank=True, default='13:28:42', max_length=180),
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo_task',
        ),
    ]
